<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BTS</name>
   <tag></tag>
   <elementGuidId>440024f1-2564-41d3-be37-12b0b2d1d67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Type__TypeElement-sc-goli3j-0.kjfRyT.nk6UgB4GUYNoAcPtAQaG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchPage']/div/div/section/div[2]/div/div/div/div[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a505a834-22c8-414f-8ff2-65d78ea9f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Type__TypeElement-sc-goli3j-0 kjfRyT nk6UgB4GUYNoAcPtAQaG</value>
      <webElementGuid>840e8ecb-447c-4ef0-a0c2-3d7abbaca568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>4e2ad9b0-1fac-4b2c-bcf2-930b9cc27657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BTS</value>
      <webElementGuid>bc92f30f-7009-409f-94f6-b7a6753342b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchPage&quot;)/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E khkfPsJuVBQyL_5cLT7y&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E nGARy02O1AklvHT7OBLA&quot;]/section[@class=&quot;iGyMsGo7FgYQQThBj2y9 QyANtc_r7ff_tqrf5Bvc Shelf&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E Z4InHgCs2uhk0MU93y_a&quot;]/div[@class=&quot;eITFAR9yPwhjL_2gxB09&quot;]/div[@class=&quot;HkbHLcqgUfXruL5xVi28&quot;]/div[@class=&quot;kVHQenQh3yKEk2n7Ere4&quot;]/div[@class=&quot;sm7ZnbOO1Zfg9cupYgPN&quot;]/a[@class=&quot;Nqa6Cw3RkDMV8QnYreTr&quot;]/div[@class=&quot;Type__TypeElement-sc-goli3j-0 kjfRyT nk6UgB4GUYNoAcPtAQaG&quot;]</value>
      <webElementGuid>62f3a04d-591b-4203-98ac-469c660e4055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchPage']/div/div/section/div[2]/div/div/div/div[2]/a/div</value>
      <webElementGuid>5829baa9-4438-4a15-8a1a-2380902d2371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top result'])[1]/following::div[8]</value>
      <webElementGuid>2c78ea15-73ed-4444-aaf0-0f4e52830d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profiles'])[1]/following::div[14]</value>
      <webElementGuid>b3ec9ce0-933d-45b4-838e-cad3b2515bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artist'])[1]/preceding::div[1]</value>
      <webElementGuid>71ba423e-c4d4-405b-b863-e7197284cd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Songs'])[2]/preceding::div[5]</value>
      <webElementGuid>fdb20757-c906-476f-a146-36fdc9a76df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BTS']/parent::*</value>
      <webElementGuid>ff14ade2-3f3d-4ed0-8c0a-7f9ff29b7c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>43456c7f-f487-45b1-b3ad-b87b991aa52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BTS' or . = 'BTS')]</value>
      <webElementGuid>4d9c42dd-5901-4cd1-b8e1-be8b1f361119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
