<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up_Type__TypeElement-sc-goli3j-0_e2d048</name>
   <tag></tag>
   <elementGuidId>6e97b2f9-c15e-4868-a378-5c432a5d7853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Type__TypeElement-sc-goli3j-0.ieTwfQ.QO9loc33XC50mMRUCIvf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e204494-7ef0-49b0-b465-da851da27a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Type__TypeElement-sc-goli3j-0 ieTwfQ QO9loc33XC50mMRUCIvf</value>
      <webElementGuid>a5adc979-8670-48f8-bca1-eea89491ca39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>1f52085c-703c-4017-ab1c-830e100fbe8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e0d7132a-e53b-451d-bcaf-60823b4c808b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>43a4266e-8c12-4d3d-ae62-2c3d66942019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6b72a7a1-0db8-4b14-975d-bf2b6ac02bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to listen to?</value>
      <webElementGuid>c1d39b31-995a-4018-8a24-4f544f211792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>94283cd3-4b0c-426d-a6f7-a98eee6f6c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>822f0c29-039a-4cc0-8d93-9cf3c3055837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>0a056240-bab3-468e-940c-641a30bab37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root encore-dark-theme&quot;]/div[@class=&quot;ZQftYELq0aOsg6tPbVbV&quot;]/div[@class=&quot;PHgyArRLVFknlaOm31ID&quot;]/header[@class=&quot;facDIsOQo9q7kiWc4jSg qxbaGYC8rgMLfyOuYRCM&quot;]/div[@class=&quot;rovbQsmAS_mwvpKHaVhQ&quot;]/div[@class=&quot;qHWqOt_TYlFxiF0Dm2fD&quot;]/div[@class=&quot;g3Xinb8x23n81ejvS9Uj&quot;]/form[1]/input[@class=&quot;Type__TypeElement-sc-goli3j-0 ieTwfQ QO9loc33XC50mMRUCIvf&quot;]</value>
      <webElementGuid>582dfa97-0833-47db-a691-fc2fcfa1e889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='b']</value>
      <webElementGuid>12349c01-3842-4399-b158-359211e898d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/header/div[3]/div/div/form/input</value>
      <webElementGuid>91c8feb5-774a-42a1-9f75-2ba32fd10ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>86b5100a-6966-4d46-a4c5-b8cade38edca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'What do you want to listen to?']</value>
      <webElementGuid>9e405916-9f22-49a2-82a5-b008a985c7ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
