<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MasukDaftar</name>
   <tag></tag>
   <elementGuidId>40e07ee6-88fe-4e28-9c57-363450ad84f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_masukDaftarHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_masukDaftarHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a51d30cf-da4a-4a75-94c9-c584ca57c297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_masukDaftarHeader</value>
      <webElementGuid>853cc09d-1fee-4aef-9580-af50eda0490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-custom-button-v2 undefined primary-button</value>
      <webElementGuid>930fa10f-8f7a-4e58-918c-4862ecbe55b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk/Daftar</value>
      <webElementGuid>8572eab2-7c8a-4451-a900-8a51fa1e40ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_masukDaftarHeader&quot;)</value>
      <webElementGuid>00684c30-73b8-4c33-a8a4-9cb2524e76fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_masukDaftarHeader']</value>
      <webElementGuid>25919261-b095-41e6-b5fe-cb0935c7f0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='momotor-header']/div/nav[2]/div/div/div[2]/button</value>
      <webElementGuid>fdf7c33a-bb08-41c8-97f2-7cd4175ee2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merek motor'])[1]/preceding::button[2]</value>
      <webElementGuid>cc98d576-5bf9-4edb-89da-719bcfcb673a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::button[2]</value>
      <webElementGuid>54a797a1-d2e3-4ad4-9576-e23f1b9e353a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9f0218ec-50c7-49da-bf9d-48130ba6f2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_masukDaftarHeader' and (text() = 'Masuk/Daftar' or . = 'Masuk/Daftar')]</value>
      <webElementGuid>8990c334-c142-4d06-a76a-ce53e2eb39e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
