<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>b59a85ea-d848-4ad5-ac4b-9720e2a5833e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div[2]/nav/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44b9b5dc-14c8-4cd1-afb7-77d7313a4a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0e32239-614c-476c-b780-cbed40eaa326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ce678dd4-094c-4146-9859-3c4418a37eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-subtle UYeKN11KAw61rZoyjcgZ</value>
      <webElementGuid>81360df7-f674-4e5d-be8c-67644f29d735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search</value>
      <webElementGuid>5530eeb0-ebe5-4912-8387-37d4a3d1bc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3478bac-a3ad-4e81-b4e8-80581a849a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context-menu-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea94bbe4-037d-409e-8ac3-5a5a6cd61351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>5055239c-9fa0-4717-a084-f6e6dca395a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root encore-dark-theme&quot;]/div[@class=&quot;ZQftYELq0aOsg6tPbVbV&quot;]/div[@class=&quot;BdcvqBAid96FaHAmPYw_&quot;]/nav[@class=&quot;sqKERfoKl4KwrtHqcKOd&quot;]/div[@class=&quot;EZFyDnuQnx5hw78phLqP&quot;]/ul[@class=&quot;QuHe04rU4bj0Z5U9E2Tk&quot;]/li[@class=&quot;LU0q0itTx2613uiATSig InvalidDropTarget&quot;]/a[@class=&quot;link-subtle UYeKN11KAw61rZoyjcgZ&quot;]</value>
      <webElementGuid>85c020e5-33dd-4c15-a1d5-1bb6cb0e58e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[2]/nav/div/ul/li[2]/a</value>
      <webElementGuid>9b09ed2a-6504-4611-adb6-a0bc2ac1788c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>6c946a92-298f-45ff-8576-e4780fe0404a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[2]</value>
      <webElementGuid>b936a666-ed9c-4747-8a20-31a1d4d9f770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Library'])[1]/preceding::a[1]</value>
      <webElementGuid>f70c5100-072e-4e68-8c2e-f2ecd17405f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search')]</value>
      <webElementGuid>2af12c20-a9b8-4001-9c2e-404aa71f1e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>9fd90128-452d-49b0-a61d-5ade828ffb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>3a394775-b8a9-457c-8160-c99b8f292e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
